In [1]:
import pandas as pd
import numpy as np

# Importing Data

In [4]:
df_main = pd.read_csv('CSV Files/main.csv')

In [6]:
df_train = pd.read_csv('CSV Files/train.csv')

In [7]:
df_init = df_main.drop(['Stars'], axis = 1)
df_train = df_train[['Index', 'User_id', 'Product_id', 'Stars']]
df_train = pd.merge(df_init, df_train, how = 'left', on = ['Index', 'User_id', 'Product_id'])
df_train.Stars = df_train.Stars.fillna(0)
df_train

,Index,User_id,Product_id,Username,Review,Review_cleaned,Combination,Dry,Normal,Oily,Sensitive,Skin_Tone,Skin_Type,Eye_Color,Hair_Color,category,price,Stars
0,1,3420,157.0,allyp3,This is hands down the best cleanser I've ever...,"['hand', 'best', 'cleanser', 'ever', 'used', '...",0,0,0,0,0,Medium,Combination,Brown,Brunette,Cleanser,36.00,5.0
1,2,2483,157.0,PatTea,Unfortunately this doesn't work for everyone. ...,"['unfortunately', 'work', 'everyone', 'used', ...",0,0,0,0,0,Medium,Combination,Brown,Red,Cleanser,36.00,1.0
2,3,2715,157.0,Sabi1991,My favorite cleanser!! i love the packaging on...,"['favorite', 'cleanser', 'love', 'packaging', ...",0,0,0,0,0,No data,No data,No data,No data,Cleanser,36.00,5.0
3,4,4497,157.0,happyface2,I love all things Youth To The People! This cl...,"['love', 'thing', 'youth', 'people', 'cleanser...",0,0,0,0,0,Fair,Dry,Blue,Blonde,Cleanser,36.00,5.0
4,5,5017,157.0,kimkix34,I had a trial size of this and was obsessed. M...,"['trial', 'size', 'wa', 'obsessed', 'skin', 'f...",0,0,0,0,0,Fair,Normal,Green,Blonde,Cleanser,36.00,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13126,13127,10169,1440.0,SUSANNA,"It's great, love it. It makes skin so soft, sm...",NaN,0,0,0,0,0,No data,No data,No data,No data,Bath Oil,8.80,5.0
13127,13128,10353,1443.0,Michi,I am struggling with bowel cancer and the writ...,NaN,0,0,0,0,0,No data,No data,No data,No data,Bath Oil,49.00,5.0
13128,13129,10354,1452.0,Siii,"Good product, smells nice. Will be good for ou...",NaN,0,0,0,0,0,No data,No data,No data,No data,Bath Oil,13.95,5.0
13129,13130,8312,1452.0,nina,This Weleda Calendula Cream Bath is so soft an...,NaN,0,0,0,0,0,No data,No data,No data,No data,Bath Oil,13.95,4.0
13130,13131,8312,1452.0,Nina,This Weleda Calendula Cream Bath is the best b...,NaN,0,0,0,0,0,No data,No data,No data,No data,Bath Oil,13.95,0.0

In [8]:
df_train.groupby('category').count()

,Index,User_id,Product_id,Username,Review,Review_cleaned,Combination,Dry,Normal,Oily,Sensitive,Skin_Tone,Skin_Type,Eye_Color,Hair_Color,price,Stars
category,,,,,,,,,,,,,,,,,
Balm,220,220,220,220,220,0,220,220,220,220,220,220,220,220,220,220,220
Bath Oil,49,49,49,49,49,0,49,49,49,49,49,49,49,49,49,49,49
Bath Salts,60,60,60,60,60,0,60,60,60,60,60,60,60,60,60,60,60
Body Wash,355,355,355,355,355,0,355,355,355,355,355,355,355,355,355,355,355
Cleanser,4788,4788,4788,4788,4788,4117,4788,4788,4788,4788,4788,4788,4788,4788,4788,4788,4788
Exfoliator,194,194,194,194,194,0,194,194,194,194,194,194,194,194,194,194,194
Eye Care,449,449,449,449,449,0,449,449,449,449,449,449,449,449,449,449,449
Face Mask,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Mask,528,528,528,528,528,0,528,528,528,528,528,528,528,528,528,528,528
Mist,191,191,191,191,191,0,191,191,191,191,191,191,191,191,191,191,191
Moisturiser,732,732,732,732,732,0,732,732,732,732,732,732,732,732,732,732,732
Moisturizer,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560,2560
Oil,325,325,325,325,325,0,325,325,325,325,325,325,325,325,325,325,325
Peel,67,67,67,67,67,0,67,67,67,67,67,67,67,67,67,67,67
Serum,437,437,437,437,437,0,437,437,437,437,437,437,437,437,437,437,437
Toner,204,204,204,204,204,0,204,204,204,204,204,204,204,204,204,204,204
Treatment,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948,1948

Moisturiser and Moisturizer should be the same

In [9]:
df_train['category_2'] = df_train['category'].apply(lambda x: 'Moisturiser' if x == 'Moisturizer' else x)

# Data preprocessing + Algorithm

## Create User User Dataframe

In [10]:
user_user_df = df_train.drop(columns = ['Index'])

In [11]:
user_user_df.shape

(13131, 18)

## Interaction Matrix

In [12]:
users_item_matrix = user_user_df.pivot_table(index = 'User_id',
                                             columns = 'Product_id',
                                             values = 'Stars',
                                             aggfunc= np.mean).fillna(0) 
#aggfunc because there are customers who bought twice but different rating

users_item_matrix.head(10)

Product_id,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,1426.0,1427.0,1428.0,1431.0,1434.0,1435.0,1436.0,1440.0,1443.0,1452.0
User_id,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
users_item_matrix.shape

(9837, 1075)

In [14]:
users_item_matrix.values.mean()*100

0.4575581986377962

## AuthEncoder to fill in sparse matrix

In [15]:
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.models import Model


def autoEncoder(X):
    '''
    Autoencoder for Collaborative Filter Model
    '''

    # Input, take the raw interaction matrix
    input_layer = Input(shape=(X.shape[1],), name='UserScore')
    
    # Encoder
    # -----------------------------
    enc = Dense(512, activation='selu', name='EncLayer1')(input_layer)

    # Latent Space
    # -----------------------------
    lat_space = Dense(256, activation='selu', name='LatentSpace')(enc)
    lat_space = Dropout(0.8, name='Dropout')(lat_space) # L2 norm regularization term

    # Decoder
    # -----------------------------
    dec = Dense(512, activation='selu', name='DecLayer1')(lat_space)

    # Output
    output_layer = Dense(X.shape[1], activation='linear', name='UserScorePred')(dec) 
    # the output target is continus score, therefore the activation is linear
    #  regression {x-f(x)}
    # this model maps an input to its reconstruction
    model = Model(input_layer, output_layer)    
    
    return model

2023-04-22 13:41:14.386844: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [16]:
# input
# input x
X = users_item_matrix.values
y = users_item_matrix.values

In [17]:
# Build model
model = autoEncoder(X)

model.compile(optimizer = Adam(learning_rate=0.0001), loss='mse')
    
model.summary()

Metal device set to: Apple M1 Pro

2023-04-22 13:41:17.352656: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-22 13:41:17.353241: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-04-22 13:41:17.353275: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 UserScore (InputLayer)      [(None, 1075)]            0

 EncLayer1 (Dense)           (None, 512)               550912

 LatentSpace (Dense)         (None, 256)               131328

 Dropout (Dropout)           (None, 256)               0

 DecLayer1 (Dense)           (None, 512)               131584

 UserScorePred (Dense)       (None, 1075)              551475

=================================================================
Total params: 1,365,299
Trainable params: 1,365,299
Non-trainable params: 0
_________________________________________________________________

In [18]:
model.fit(x=X, y=y,
          epochs=20,
          batch_size=64,
          shuffle=True,
          validation_split=0.1)

Epoch 1/20

2023-04-22 13:41:18.004704: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

139/139 [==============================] - 3s 19ms/step - loss: 0.1911 - val_loss: 0.0523
Epoch 2/20

2023-04-22 13:41:20.970335: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

139/139 [==============================] - 2s 17ms/step - loss: 0.0918 - val_loss: 0.0374
Epoch 3/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0560 - val_loss: 0.0307
Epoch 4/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0401 - val_loss: 0.0272
Epoch 5/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0321 - val_loss: 0.0253
Epoch 6/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0278 - val_loss: 0.0241
Epoch 7/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0253 - val_loss: 0.0234
Epoch 8/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0237 - val_loss: 0.0229
Epoch 9/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0227 - val_loss: 0.0226
Epoch 10/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0220 - val_loss: 0.0224
Epoch 11/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0216 - val_loss: 0.0222
Epoch 12/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0212 - val_loss: 0.0221
Epoch 13/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0209 - val_loss: 0.0220
Epoch 14/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0208 - val_loss: 0.0220
Epoch 15/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0206 - val_loss: 0.0219
Epoch 16/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0205 - val_loss: 0.0219
Epoch 17/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0204 - val_loss: 0.0219
Epoch 18/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0203 - val_loss: 0.0219
Epoch 19/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0203 - val_loss: 0.0219
Epoch 20/20
139/139 [==============================] - 2s 17ms/step - loss: 0.0202 - val_loss: 0.0219

## Fill in 0s in the matrix

In [19]:
# Predict new Matrix Interactions
# set score zero on cosmetics
# because we only want to predict the scores of those games that users do not have interactions before
#f(x)

new_matrix = model.predict(X) * (X == 0)

 20/308 [>.............................] - ETA: 1s

2023-04-22 13:42:05.537172: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

308/308 [==============================] - 2s 6ms/step

In [20]:
# converting the reconstructed matrix back to a Pandas dataframe
new_users_item_matrix  = pd.DataFrame(new_matrix, 
                                          columns = users_item_matrix.columns, 
                                          index   = users_item_matrix.index)
new_users_item_matrix.head()

Product_id,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,1426.0,1427.0,1428.0,1431.0,1434.0,1435.0,1436.0,1440.0,1443.0,1452.0
User_id,,,,,,,,,,,,,,,,,,,,,
0,-0.003286,0.002131,-0.018071,0.006921,0.007241,0.000781,0.005784,-0.025260,-0.006548,-0.014687,...,-0.009377,0.022027,0.003623,-0.001955,0.008381,-0.001571,-0.005962,0.004522,-0.013264,0.017487
1,0.026297,0.019633,0.011827,0.014026,0.014387,0.011510,-0.020918,0.011288,0.008201,0.023617,...,-0.006376,0.016396,0.005086,-0.003448,-0.005024,0.001094,0.005503,0.014885,0.001468,0.001368
2,0.022688,0.015360,-0.000311,-0.001582,0.013399,0.008820,0.000495,0.008175,0.008808,0.018272,...,-0.010230,0.014800,0.001802,0.001318,-0.002970,-0.004754,0.006885,0.017902,-0.004950,-0.008392
3,-0.014443,-0.008452,0.040010,0.027109,0.026237,-0.001811,0.034535,0.037241,-0.040183,0.019098,...,0.007892,0.025111,-0.004285,0.000403,-0.009338,0.004305,-0.009546,0.007468,-0.012076,-0.014286
4,0.047542,0.052547,-0.009437,0.009587,-0.021684,-0.036569,0.004987,-0.066051,0.047014,0.008612,...,0.013311,0.019133,-0.009261,0.013258,-0.002835,0.004515,-0.004567,0.000313,-0.000341,-0.001320

## Similarity between users

In [21]:
#Matrix Normalization - https://medium.com/grabngoinfo/recommendation-system-user-based-collaborative-filtering-a2e76e3e15c4

new_users_item_norm = new_users_item_matrix.subtract(new_users_item_matrix.mean(axis=1), axis = 'rows')
new_users_item_norm.head()

Product_id,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,1426.0,1427.0,1428.0,1431.0,1434.0,1435.0,1436.0,1440.0,1443.0,1452.0
User_id,,,,,,,,,,,,,,,,,,,,,
0,-0.006079,-0.000662,-0.020863,0.004128,0.004449,-0.002012,0.002992,-0.028053,-0.009340,-0.017480,...,-0.012170,0.019235,0.000830,-0.004748,0.005588,-0.004363,-0.008755,0.001730,-0.016057,0.014694
1,0.023425,0.016761,0.008955,0.011154,0.011516,0.008638,-0.023790,0.008417,0.005329,0.020745,...,-0.009247,0.013524,0.002214,-0.006319,-0.007895,-0.001778,0.002631,0.012014,-0.001404,-0.001504
2,0.019752,0.012424,-0.003247,-0.004518,0.010463,0.005884,-0.002441,0.005239,0.005872,0.015336,...,-0.013166,0.011864,-0.001134,-0.001618,-0.005906,-0.007690,0.003949,0.014966,-0.007886,-0.011328
3,-0.017651,-0.011661,0.036801,0.023900,0.023029,-0.005020,0.031326,0.034033,-0.043391,0.015890,...,0.004683,0.021902,-0.007494,-0.002806,-0.012546,0.001097,-0.012755,0.004259,-0.015285,-0.017495
4,0.043671,0.048677,-0.013308,0.005716,-0.025555,-0.040440,0.001116,-0.069921,0.043144,0.004741,...,0.009441,0.015263,-0.013131,0.009387,-0.006706,0.000644,-0.008437,-0.003558,-0.004212,-0.005190

### Simple Similarity looking at the ratings provided by users only

In [22]:
# User similarity matrix using Pearson correlation
user_similarity = new_users_item_norm.T.corr()
user_similarity.head()

User_id,0,1,2,3,4,5,6,7,8,9,...,10340,10341,10342,10344,10345,10346,10347,10348,10353,10354
User_id,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.179451,0.166124,0.053224,0.158277,0.033964,0.057141,0.180857,-0.016572,0.104665,...,-0.006891,-0.030067,-0.030067,-0.030067,-0.030067,-0.030067,0.095366,0.014780,0.032055,0.016089
1,0.179451,1.000000,0.760570,0.295766,0.158330,0.278562,0.174742,0.769934,0.192982,0.189003,...,0.050522,0.024178,0.024178,0.024178,0.024178,0.024178,0.042623,0.054937,0.067324,0.034568
2,0.166124,0.760570,1.000000,0.300263,0.217317,0.271093,0.168011,0.716687,0.187446,0.202104,...,0.146120,0.003995,0.003995,0.003995,0.003995,0.003995,0.055076,0.117185,-0.010408,-0.017474
3,0.053224,0.295766,0.300263,1.000000,0.065067,0.060362,0.069286,0.262946,0.126250,0.081467,...,-0.028782,-0.021942,-0.021942,-0.021942,-0.021942,-0.021942,0.030428,-0.010283,-0.020589,-0.002981
4,0.158277,0.158330,0.217317,0.065067,1.000000,0.040437,0.003096,0.126629,0.010406,0.106447,...,0.041887,-0.038630,-0.038630,-0.038630,-0.038630,-0.038630,0.011595,0.048726,0.058879,0.069172

## Features only Recommendation System

In [23]:
user_properties = user_user_df[['User_id','Skin_Tone','Skin_Type','Eye_Color','Hair_Color']]

In [24]:
# Need to run through the user properties because some users indicated different data for different entries
# decided to keep anything that is not 'No data' if there are duplicates
cleansed_user_properties = []
user_list = np.sort(user_properties.User_id.unique())
counter = 0

for i in user_list:
    holder = user_properties[user_properties.User_id == i]
    if len(holder.User_id) == 1:
        Skin_Tone = holder.Skin_Tone.to_list()[0]
        Skin_Type = holder.Skin_Type.to_list()[0]
        Eye_Color = holder.Eye_Color.to_list()[0]
        Hair_Color = holder.Hair_Color.to_list()[0]
        counter += 1
    else:
        for j, row in enumerate(holder.itertuples()):
            if j == 0:
                Skin_Tone = row.Skin_Tone
                Skin_Type = row.Skin_Type
                Eye_Color = row.Eye_Color
                Hair_Color = row.Hair_Color
            else:
                Skin_Tone2 = row.Skin_Tone
                Skin_Type2 = row.Skin_Type
                Eye_Color2 = row.Eye_Color
                Hair_Color2 = row.Hair_Color
                if Skin_Tone2 != Skin_Tone:
                    if Skin_Tone2 != 'No data':
                        Skin_Tone = Skin_Tone2
                if Skin_Type2 != Skin_Type:
                    if Skin_Type2 != 'No data':
                        Skin_Type = Skin_Type2
                if Eye_Color2 != Eye_Color:
                    if Eye_Color2 != 'No data':
                        Eye_Color = Eye_Color2
                if Hair_Color2 != Hair_Color:
                    if Hair_Color2 != 'No data':
                        Hair_Color = Hair_Color2
        
    holding_list = [i, Skin_Tone, Skin_Type, Eye_Color, Hair_Color]          
    cleansed_user_properties.append(holding_list)
    
cleansed_user_properties_df = pd.DataFrame (cleansed_user_properties, 
                                            columns = ['User_id', 'Skin_Tone', 'Skin_Type', 'Eye_Color', 'Hair_Color',])

In [25]:
categorical_cols = ['Skin_Tone','Skin_Type','Eye_Color','Hair_Color']
from sklearn.preprocessing import LabelEncoder
# instantiate labelencoder object
le = LabelEncoder()
# apply le on categorical feature columns
cleansed_user_properties_df[categorical_cols] = cleansed_user_properties_df[categorical_cols].apply(lambda col: le.fit_transform(col))    
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [26]:
_, new_cols = np.unique(cleansed_user_properties_df[['Skin_Tone','Skin_Type','Eye_Color','Hair_Color']].to_numpy(), axis =0, return_inverse=True)
cleansed_user_properties_df['Combine_Properties'] = new_cols

In [27]:
def Recommendation_w_properties_only(selected_id, num_of_products):
    users = []
    items = []
    ratings = []
    priority = []
    
    
    # Selected User 
    selected_skin_tone = cleansed_user_properties_df[
        cleansed_user_properties_df.User_id == selected_id].Skin_Tone.to_list()[0]
    selected_skin_type = cleansed_user_properties_df[
        cleansed_user_properties_df.User_id == selected_id].Skin_Type.to_list()[0]
    selected_eye_color = cleansed_user_properties_df[
        cleansed_user_properties_df.User_id == selected_id].Eye_Color.to_list()[0]
    selected_hair_color = cleansed_user_properties_df[
        cleansed_user_properties_df.User_id == selected_id].Hair_Color.to_list()[0]
    
    # Find users who have 4 same properties as the Selected User
    same_users_list_4 = cleansed_user_properties_df[(cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
                                                 (cleansed_user_properties_df.Skin_Type == selected_skin_type) &
                                                 (cleansed_user_properties_df.Eye_Color == selected_eye_color) &
                                                 (cleansed_user_properties_df.Hair_Color == selected_hair_color)
                                                 ].User_id.to_list()
    
    # Drop the Selected User
    same_users_list_4.remove(selected_id)
    leng = len(same_users_list_4)
    
    for i in range(leng):
        user = same_users_list_4[i]
        item_list = user_user_df[user_user_df.User_id == i].Product_id.values.tolist()
        rating_list = user_user_df[user_user_df.User_id == i].Stars.values.tolist()
        for j in range(len(item_list)):
            item = item_list[j]
            rating = rating_list[j]
            items.append(item)
            ratings.append(rating)
            users.append(user)
            priority.append(4)
            
    if len(items) < num_of_products:
        
        # Next Set of Users
        same_users_list_3a = cleansed_user_properties_df[
            (cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
            (cleansed_user_properties_df.Skin_Type == selected_skin_type) &
            (cleansed_user_properties_df.Eye_Color == selected_eye_color)
        ].User_id.to_list()

        same_users_list_3b = cleansed_user_properties_df[
            (cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
            (cleansed_user_properties_df.Eye_Color == selected_eye_color) &
            (cleansed_user_properties_df.Hair_Color == selected_hair_color)
        ].User_id.to_list()

        same_users_list_3c = cleansed_user_properties_df[
            (cleansed_user_properties_df.Skin_Type == selected_skin_type) &
            (cleansed_user_properties_df.Eye_Color == selected_eye_color) &
            (cleansed_user_properties_df.Hair_Color == selected_hair_color)
        ].User_id.to_list()

        same_users_list_3d = cleansed_user_properties_df[
            (cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
            (cleansed_user_properties_df.Skin_Type == selected_skin_type) &
            (cleansed_user_properties_df.Hair_Color == selected_hair_color)
        ].User_id.to_list()
        
        list1 = [x for x in same_users_list_3a if x not in same_users_list_4]
        list2 = [x for x in same_users_list_3b if x not in same_users_list_4]
        list3 = [x for x in same_users_list_3c if x not in same_users_list_4]
        list4 = [x for x in same_users_list_3d if x not in same_users_list_4]
        combined_list = list1 + list2 + list3 + list4
        final_list_3 = []
        for i in combined_list:
            if i not in final_list_3:
                final_list_3.append(i)
        
        similar_users_found = final_list_3 + same_users_list_4
        
        for i in final_list_3:
            user = i
            item_list = user_user_df[user_user_df.User_id == i].Product_id.values.tolist()
            rating_list = user_user_df[user_user_df.User_id == i].Stars.values.tolist()
            for j in range(len(item_list)):
                item = item_list[j]
                rating = rating_list[j]
                items.append(item)
                ratings.append(rating)
                users.append(user)
                priority.append(3)
        
        if len(items) < num_of_products:
            
            # Next Set of Users
            same_users_list_2a = cleansed_user_properties_df[
                (cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
                (cleansed_user_properties_df.Skin_Type == selected_skin_type)
            ].User_id.to_list()
            
            same_users_list_2b = cleansed_user_properties_df[
                (cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
                (cleansed_user_properties_df.Hair_Color == selected_hair_color)
            ].User_id.to_list()
            
            same_users_list_2c = cleansed_user_properties_df[
                (cleansed_user_properties_df.Skin_Tone == selected_skin_tone) &
                (cleansed_user_properties_df.Eye_Color == selected_eye_color)
            ].User_id.to_list()
            
            
            same_users_list_2d = cleansed_user_properties_df[
                (cleansed_user_properties_df.Skin_Type == selected_skin_type) &
                (cleansed_user_properties_df.Eye_Color == selected_eye_color)
            ].User_id.to_list()
            
            
            same_users_list_2e = cleansed_user_properties_df[
                (cleansed_user_properties_df.Skin_Type == selected_skin_type) &
                (cleansed_user_properties_df.Hair_Color == selected_hair_color)
            ].User_id.to_list()
            
            
            same_users_list_2f = cleansed_user_properties_df[
                (cleansed_user_properties_df.Eye_Color == selected_eye_color) &
                (cleansed_user_properties_df.Hair_Color == selected_hair_color)
            ].User_id.to_list()
            
            
            list1 = [x for x in same_users_list_2a if x not in similar_users_found]
            list2 = [x for x in same_users_list_2b if x not in similar_users_found]
            list3 = [x for x in same_users_list_2c if x not in similar_users_found]
            list4 = [x for x in same_users_list_2d if x not in similar_users_found]
            list5 = [x for x in same_users_list_2e if x not in similar_users_found]
            list6 = [x for x in same_users_list_2f if x not in similar_users_found]
            
            combined_list = list1 + list2 + list3 + list4 + list5 + list6
            final_list_2 = []
            for i in combined_list:
                if i not in final_list_2:
                    final_list_2.append(i)
                
            similar_users_found = similar_users_found + final_list_2
            
            for i in final_list_2:
                user = i
                item_list = user_user_df[user_user_df.User_id == i].Product_id.values.tolist()
                rating_list = user_user_df[user_user_df.User_id == i].Stars.values.tolist()
                for j in range(len(item_list)):
                    item = item_list[j]
                    rating = rating_list[j]
                    items.append(item)
                    ratings.append(rating)
                    users.append(user)
                    priority.append(2)
                
            if len(items) < num_of_products:
            
                # Next Set of Users
                same_users_list_1a = cleansed_user_properties_df[
                    (cleansed_user_properties_df.Skin_Tone == selected_skin_tone)
                                                                ].User_id.to_list()

                same_users_list_1b = cleansed_user_properties_df[
                    (cleansed_user_properties_df.Hair_Color == selected_hair_color)
                                                                ].User_id.to_list()

                same_users_list_1c = cleansed_user_properties_df[
                    (cleansed_user_properties_df.Eye_Color == selected_eye_color)
                                                                ].User_id.to_list()


                same_users_list_1d = cleansed_user_properties_df[
                    (cleansed_user_properties_df.Skin_Type == selected_skin_type)
                                                                ].User_id.to_list()


                list1 = [x for x in same_users_list_1a if x not in similar_users_found]
                list2 = [x for x in same_users_list_1b if x not in similar_users_found]
                list3 = [x for x in same_users_list_1c if x not in similar_users_found]
                list4 = [x for x in same_users_list_1d if x not in similar_users_found]

                combined_list = list1 + list2 + list3 + list4
                final_list_1 = []
                for i in combined_list:
                    if i not in final_list_1:
                        final_list_1.append(i)

                similar_users_found = similar_users_found + final_list_1

                for i in final_list_1:
                    user = i
                    item_list = user_user_df[user_user_df.User_id == i].Product_id.values.tolist()
                    rating_list = user_user_df[user_user_df.User_id == i].Stars.values.tolist()
                    for j in range(len(item_list)):
                        item = item_list[j]
                        rating = rating_list[j]
                        items.append(item)
                        ratings.append(rating)
                        users.append(user)
                        priority.append(1)
    
    data_tuples = list(zip(items,ratings,users,priority))
    df = pd.DataFrame(data_tuples, columns=['Product_id','Stars','Users_id','Priority'])
    sorted_df = df.sort_values(by=['Priority', 'Stars'], ascending=False).drop_duplicates(subset=['Product_id'])
    Recommended_list = sorted_df.Product_id[0:num_of_products]
    return Recommended_list

## Function to recommend user - Simple

In [28]:
def Recommendation(selected_id, threshold,num_similar_user,num_products):
    # Remove selected user from the similarity df
    user_similarity_df = user_similarity.drop(index=selected_id)
    # number of similar user to consider to reduce processing time
    num_similar_user = num_similar_user
    # finding similar users based on threshold provided
    similar_users = user_similarity_df[user_similarity_df[selected_id]>threshold][selected_id].sort_values(ascending=False
                                                                                                  )[:num_similar_user]
    # finding items that were purchased by selected user
    holder = users_item_matrix[users_item_matrix.index == selected_id]
    holder = holder.loc[:,(holder != 0).any(axis=0)]
    # Similar Users items that were purchased
    similar_user_items = new_users_item_matrix[new_users_item_matrix.index.isin(similar_users.index)]
    # Remove items that selected user has purchased before
    similar_user_items = similar_user_items.drop(holder.columns,axis=1,  errors='ignore')
    
    # Select top m item
    m = num_products
    
    # A dictionary to store item scores
    item_score = {}
    # Loop through items
    if similar_users.size != 0:
        for i in similar_user_items.columns:
            # Get the ratings for movie i
            item_rating = similar_user_items[i]
            # Create a variable to store the score
            total = 0
            # Create a variable to store the number of scores
            count = 0
            # Loop through similar users
            for u in similar_users.index:
                # Score is the sum of user similarity score multiply by the movie rating
                score = similar_users[u] * item_rating[u]
                # Add the score to the total score for the movie so far
                total += score
                # Add 1 to the count
                count +=1
            # Get the average score for the item
            item_score[i] = total / count
            
        # Convert dictionary to pandas dataframe
        item_score = pd.DataFrame(item_score.items(), columns=['Item', 'Item_score'])

        # Sort the movies by score
        ranked_item_score = item_score.sort_values(by='Item_score', ascending=False)
        ranked_item = ranked_item_score.head(m).Item.to_list()
        
        if len(ranked_item) < 10:
            next_list = Recommendation_w_properties_only(selected_id, num_of_products)
            ranked_item.extend(next_list)
            new_list = []
            for item in ranked_item:
                if item not in new_list:
                    new_list.append(item)
            ranked_item = new_list
            ranked_item = ranked_item[0:m].to_list()
        
    else:
        
        ranked_item = Recommendation_w_properties_only(selected_id, num_of_products)
        ranked_item = ranked_item[0:m].to_list()

    return ranked_item

# Evaluation

## Importing the test users

In [30]:
df_test=pd.read_csv('CSV Files/test.csv')

In [31]:
train_set_userids = set(df_train['User_id'].unique())
test_set_userids = set(df_test['User_id'].unique())
matching_users = train_set_userids.intersection(test_set_userids)

In [32]:
user_list = pd.DataFrame(matching_users,columns=['User_id'])
user_list

     User_id
0       8193
1       2051
2       8196
3       6154
4       6155
..       ...
502     8172
503     4081
504     6134
505     8182
506     8186

[507 rows x 1 columns]

In [33]:
user_list.to_csv('user_list.csv', index=False)

In [34]:
user_list = pd.read_csv('user_list.csv').User_id.unique()
user_list

array([ 8193,  2051,  8196,  6154,  6155,  6159,  8207,  8213,  4119,
        4120,  8223,  8224,  4129,  2042,  8234,  6194,  8261,  6215,
        6217,  8271,    81,    86,    88,    90,  2144,  4193,  8288,
        8294,  8295,   104,  8301,  6255,  8303,  4210,  8312,  8319,
        4227,  8329,  2195,   169,  8365,  4279,  2233,  8385,  2243,
        6353,   213,   230,  2282,  6378,  8430,  4336,  8441,   265,
        8474,  6427,  8475,  4385,  6433,  6435,  8485,   295,  8500,
        2365,  8513,  4421,  4430,   341,  2392,  8543,   354,  4458,
        2414,   368,  8566,  8568,  4485,   393,  8585,  8590,  4497,
        4501,  2458,  8611,  6579,  8627,   440,  6601,  4558,   465,
        2513,  4562,  8660,  8664,  2527,  8671,  8673,  6633,  4587,
        4588,   496,  6644,  8695,  2561,  4610,   524,  8717,  4630,
        8730,  8731,   544,  8738,   552,   553,  8750,  6707,  4673,
        8785,  2654,  8800,  2661,   614,  2670,  6777,  2685,  4742,
        8842,  8844,  6799,   659,   664,   665,  4765,  6820,  2732,
         689,   694,   696,  4806,   713,  4813,  6891,  2797,  6895,
        6896,  8943,  6899,  6900,  6902,  6904,  6907,   765,  2813,
        6909,  6912,  2819,  6915,  6916,  6917,  8967,  6922,  6931,
        6933,  6937,  4896,  6946,  6952,  6953,  6954,  4918,   828,
        2877,  4925,  6975,  6977,  6978,  6979,   836,  6981,  6982,
        6983,  9028,  6988,  6989,   846,  6991,  6992,  6994,   858,
        7005,  7006,  9055,  7008,   866,  4963,  7010,  4969,  7018,
        7020,  7022,  7029,  7031,  7036,  7037,  7041,  7043,  7046,
        7048,  7050,  9099,  7055,  7056,  7057,  7060,  5014,  7069,
        7072,  7073,  2978,  7075,  7080,  7084,  7085,  7089,  9140,
        7098,  7100,  3008,  7115,   975,  7119,   980,  7124,  7133,
        7134,   998,  7143,  7144,  9191,  7153,  1011,  7161,  5119,
        7167,  7169,  5122,  7171,  7176,  7183,  1047,  3096,  7194,
        7195,  3102,  5152,  7200,  7203,  1061,  5159,  1068,  1069,
        3118,  7227,  7229,  7232,  7233,  7235,  5189,  7237,  1096,
        3144,  5193,  9294,  3151,  5201,  7249,  9298,  1108,  7252,
        7253,  7254,  7255,  7256,  7257,  7259,  7260,  7263,  3169,
        7265,  7271,  7276,  7277,  5233,  5236,  3191,  5239,  7293,
        1152,  5249,  7299,  3207,  7303,  7305,  7309,  7313,  7317,
        3226,  7327,  7328,  7338,  7339,  7352,  7354,  1213,  5312,
        7361,  7365,  5321,  7373,  1235,  7379,  5333,  7382,  1242,
        5340,  7398,  7413,  7414,  7415,  3324,  1277,  5374,  7422,
        7433,  7437,  5390,  9492,  3352,  7448,  7450,  3356,  7456,
        7459,  5412,  7460,  7465,  3373,  5421,  3384,  5433,  7486,
        7494,  7503,  7504,  7505,  7506,  7507,  7514,  7519,  1385,
        5488,  5489,  7546,  9596,  3461,  7561,  9610,  5517,  7566,
        7573,  7579,  7581,  3488,  3494,  7591,  3497,  3500,  7599,
        7603,  1467,  1471,  5579,  5580,  3538,  7634,  7640,  3552,
        7648,  7650,  7658,  7660,  5614,  1520,  7665,  7667,  7670,
        3582,  7683,  1546,  7690,  3597,  5646,  5652,  9750,  5659,
        1564,  1565,  5661,  3615,  7710,  3618,  7716,  1573,  7717,
        7724,  7727,  9776,  7733,  7735,  5689,  7750,  7753,  3665,
        3667,  7768,  5738,  7788,  1647,  1653,  7798,  7804,  7810,
        5764,  7817,  5770,  7819,  1682,  7827,  5782,  7838,  7844,
        7847,  5806,  7855,  7858,  5813,  7884,  7886,  7887,  3795,
        5855,  7906,  7913,  9962,  1773,  1781,  7929,  3839,  7937,
        7942,  1801,  7948,  7954,  5915,  7963,  1828,  7975,  7987,
        7991,  7992,  3899, 10048,  1861,  8007,  8008,  8018,  8025,
        5982,  8033,  1893,  1906,  1907,  1908,  8051,  8054,  8070,
        3981,  8088,  6057,  8105,  8117,  8120,  1986,  6092,  6096,
        2007,  4055,  8151,  6109,  4063,  8162,  8169,  8172,  4081,
        6134,  8182,  8186])

## Find recommendation for test users

In [35]:
num_of_products = 10
reco_products_user = []
counter = 0
for i in user_list:
    reco_products = Recommendation(i,0.3,10,num_of_products)
    reco_products_user.append(reco_products)
    counter += 1
    print("Remaining number of users is", len(user_list) - counter)
    
reco_tuples = list(zip(user_list,reco_products_user))
Ten_Recommendation_Each_User = pd.DataFrame(reco_tuples, columns=['User_id','Product_ids'])

Remaining number of users is 506
Remaining number of users is 505
Remaining number of users is 504
Remaining number of users is 503
Remaining number of users is 502
Remaining number of users is 501
Remaining number of users is 500
Remaining number of users is 499
Remaining number of users is 498
Remaining number of users is 497
Remaining number of users is 496
Remaining number of users is 495
Remaining number of users is 494
Remaining number of users is 493
Remaining number of users is 492
Remaining number of users is 491
Remaining number of users is 490
Remaining number of users is 489
Remaining number of users is 488
Remaining number of users is 487
Remaining number of users is 486
Remaining number of users is 485
Remaining number of users is 484
Remaining number of users is 483
Remaining number of users is 482
Remaining number of users is 481
Remaining number of users is 480
Remaining number of users is 479
Remaining number of users is 478
Remaining number of users is 477
Remaining number of users is 476
Remaining number of users is 475
Remaining number of users is 474
Remaining number of users is 473
Remaining number of users is 472
Remaining number of users is 471
Remaining number of users is 470
Remaining number of users is 469
Remaining number of users is 468
Remaining number of users is 467
Remaining number of users is 466
Remaining number of users is 465
Remaining number of users is 464
Remaining number of users is 463
Remaining number of users is 462
Remaining number of users is 461
Remaining number of users is 460
Remaining number of users is 459
Remaining number of users is 458
Remaining number of users is 457
Remaining number of users is 456
Remaining number of users is 455
Remaining number of users is 454
Remaining number of users is 453
Remaining number of users is 452
Remaining number of users is 451
Remaining number of users is 450
Remaining number of users is 449
Remaining number of users is 448
Remaining number of users is 447
Remaining number of users is 446
Remaining number of users is 445
Remaining number of users is 444
Remaining number of users is 443
Remaining number of users is 442
Remaining number of users is 441
Remaining number of users is 440
Remaining number of users is 439
Remaining number of users is 438
Remaining number of users is 437
Remaining number of users is 436
Remaining number of users is 435
Remaining number of users is 434
Remaining number of users is 433
Remaining number of users is 432
Remaining number of users is 431
Remaining number of users is 430
Remaining number of users is 429
Remaining number of users is 428
Remaining number of users is 427
Remaining number of users is 426
Remaining number of users is 425
Remaining number of users is 424
Remaining number of users is 423
Remaining number of users is 422
Remaining number of users is 421
Remaining number of users is 420
Remaining number of users is 419
Remaining number of users is 418
Remaining number of users is 417
Remaining number of users is 416
Remaining number of users is 415
Remaining number of users is 414
Remaining number of users is 413
Remaining number of users is 412
Remaining number of users is 411
Remaining number of users is 410
Remaining number of users is 409
Remaining number of users is 408
Remaining number of users is 407
Remaining number of users is 406
Remaining number of users is 405
Remaining number of users is 404
Remaining number of users is 403
Remaining number of users is 402
Remaining number of users is 401
Remaining number of users is 400
Remaining number of users is 399
Remaining number of users is 398
Remaining number of users is 397
Remaining number of users is 396
Remaining number of users is 395
Remaining number of users is 394
Remaining number of users is 393
Remaining number of users is 392
Remaining number of users is 391
Remaining number of users is 390
Remaining number of users is 389
Remaining number of users is 388
Remaining number of users is 387
Remaining number of users is 386
Remaining number of users is 385
Remaining number of users is 384
Remaining number of users is 383
Remaining number of users is 382
Remaining number of users is 381
Remaining number of users is 380
Remaining number of users is 379
Remaining number of users is 378
Remaining number of users is 377
Remaining number of users is 376
Remaining number of users is 375
Remaining number of users is 374
Remaining number of users is 373
Remaining number of users is 372
Remaining number of users is 371
Remaining number of users is 370
Remaining number of users is 369
Remaining number of users is 368
Remaining number of users is 367
Remaining number of users is 366
Remaining number of users is 365
Remaining number of users is 364
Remaining number of users is 363
Remaining number of users is 362
Remaining number of users is 361
Remaining number of users is 360
Remaining number of users is 359
Remaining number of users is 358
Remaining number of users is 357
Remaining number of users is 356
Remaining number of users is 355
Remaining number of users is 354
Remaining number of users is 353
Remaining number of users is 352
Remaining number of users is 351
Remaining number of users is 350
Remaining number of users is 349
Remaining number of users is 348
Remaining number of users is 347
Remaining number of users is 346
Remaining number of users is 345
Remaining number of users is 344
Remaining number of users is 343
Remaining number of users is 342
Remaining number of users is 341
Remaining number of users is 340
Remaining number of users is 339
Remaining number of users is 338
Remaining number of users is 337
Remaining number of users is 336
Remaining number of users is 335
Remaining number of users is 334
Remaining number of users is 333
Remaining number of users is 332
Remaining number of users is 331
Remaining number of users is 330
Remaining number of users is 329
Remaining number of users is 328
Remaining number of users is 327
Remaining number of users is 326
Remaining number of users is 325
Remaining number of users is 324
Remaining number of users is 323
Remaining number of users is 322
Remaining number of users is 321
Remaining number of users is 320
Remaining number of users is 319
Remaining number of users is 318
Remaining number of users is 317
Remaining number of users is 316
Remaining number of users is 315
Remaining number of users is 314
Remaining number of users is 313
Remaining number of users is 312
Remaining number of users is 311
Remaining number of users is 310
Remaining number of users is 309
Remaining number of users is 308
Remaining number of users is 307
Remaining number of users is 306
Remaining number of users is 305
Remaining number of users is 304
Remaining number of users is 303
Remaining number of users is 302
Remaining number of users is 301
Remaining number of users is 300
Remaining number of users is 299
Remaining number of users is 298
Remaining number of users is 297
Remaining number of users is 296
Remaining number of users is 295
Remaining number of users is 294
Remaining number of users is 293
Remaining number of users is 292
Remaining number of users is 291
Remaining number of users is 290
Remaining number of users is 289
Remaining number of users is 288
Remaining number of users is 287
Remaining number of users is 286
Remaining number of users is 285
Remaining number of users is 284
Remaining number of users is 283
Remaining number of users is 282
Remaining number of users is 281
Remaining number of users is 280
Remaining number of users is 279
Remaining number of users is 278
Remaining number of users is 277
Remaining number of users is 276
Remaining number of users is 275
Remaining number of users is 274
Remaining number of users is 273
Remaining number of users is 272
Remaining number of users is 271
Remaining number of users is 270
Remaining number of users is 269
Remaining number of users is 268
Remaining number of users is 267
Remaining number of users is 266
Remaining number of users is 265
Remaining number of users is 264
Remaining number of users is 263
Remaining number of users is 262
Remaining number of users is 261
Remaining number of users is 260
Remaining number of users is 259
Remaining number of users is 258

Remaining number of users is 257
Remaining number of users is 256
Remaining number of users is 255
Remaining number of users is 254
Remaining number of users is 253
Remaining number of users is 252
Remaining number of users is 251
Remaining number of users is 250
Remaining number of users is 249
Remaining number of users is 248
Remaining number of users is 247
Remaining number of users is 246
Remaining number of users is 245
Remaining number of users is 244
Remaining number of users is 243
Remaining number of users is 242
Remaining number of users is 241
Remaining number of users is 240
Remaining number of users is 239
Remaining number of users is 238
Remaining number of users is 237
Remaining number of users is 236
Remaining number of users is 235
Remaining number of users is 234
Remaining number of users is 233
Remaining number of users is 232
Remaining number of users is 231
Remaining number of users is 230
Remaining number of users is 229
Remaining number of users is 228
Remaining number of users is 227
Remaining number of users is 226
Remaining number of users is 225
Remaining number of users is 224
Remaining number of users is 223
Remaining number of users is 222
Remaining number of users is 221
Remaining number of users is 220
Remaining number of users is 219
Remaining number of users is 218
Remaining number of users is 217
Remaining number of users is 216
Remaining number of users is 215
Remaining number of users is 214
Remaining number of users is 213
Remaining number of users is 212
Remaining number of users is 211
Remaining number of users is 210
Remaining number of users is 209
Remaining number of users is 208
Remaining number of users is 207
Remaining number of users is 206
Remaining number of users is 205
Remaining number of users is 204
Remaining number of users is 203
Remaining number of users is 202
Remaining number of users is 201
Remaining number of users is 200
Remaining number of users is 199
Remaining number of users is 198
Remaining number of users is 197
Remaining number of users is 196
Remaining number of users is 195
Remaining number of users is 194
Remaining number of users is 193
Remaining number of users is 192
Remaining number of users is 191
Remaining number of users is 190
Remaining number of users is 189
Remaining number of users is 188
Remaining number of users is 187
Remaining number of users is 186
Remaining number of users is 185
Remaining number of users is 184
Remaining number of users is 183
Remaining number of users is 182
Remaining number of users is 181
Remaining number of users is 180
Remaining number of users is 179
Remaining number of users is 178
Remaining number of users is 177
Remaining number of users is 176
Remaining number of users is 175
Remaining number of users is 174
Remaining number of users is 173
Remaining number of users is 172
Remaining number of users is 171
Remaining number of users is 170
Remaining number of users is 169
Remaining number of users is 168
Remaining number of users is 167
Remaining number of users is 166
Remaining number of users is 165
Remaining number of users is 164
Remaining number of users is 163
Remaining number of users is 162
Remaining number of users is 161
Remaining number of users is 160
Remaining number of users is 159
Remaining number of users is 158
Remaining number of users is 157
Remaining number of users is 156
Remaining number of users is 155
Remaining number of users is 154
Remaining number of users is 153
Remaining number of users is 152
Remaining number of users is 151
Remaining number of users is 150
Remaining number of users is 149
Remaining number of users is 148
Remaining number of users is 147
Remaining number of users is 146
Remaining number of users is 145
Remaining number of users is 144
Remaining number of users is 143
Remaining number of users is 142
Remaining number of users is 141
Remaining number of users is 140
Remaining number of users is 139
Remaining number of users is 138
Remaining number of users is 137
Remaining number of users is 136
Remaining number of users is 135
Remaining number of users is 134
Remaining number of users is 133
Remaining number of users is 132
Remaining number of users is 131
Remaining number of users is 130
Remaining number of users is 129
Remaining number of users is 128
Remaining number of users is 127
Remaining number of users is 126
Remaining number of users is 125
Remaining number of users is 124
Remaining number of users is 123
Remaining number of users is 122
Remaining number of users is 121
Remaining number of users is 120
Remaining number of users is 119
Remaining number of users is 118
Remaining number of users is 117
Remaining number of users is 116
Remaining number of users is 115
Remaining number of users is 114
Remaining number of users is 113
Remaining number of users is 112
Remaining number of users is 111
Remaining number of users is 110
Remaining number of users is 109
Remaining number of users is 108
Remaining number of users is 107
Remaining number of users is 106
Remaining number of users is 105
Remaining number of users is 104
Remaining number of users is 103
Remaining number of users is 102
Remaining number of users is 101
Remaining number of users is 100
Remaining number of users is 99
Remaining number of users is 98
Remaining number of users is 97
Remaining number of users is 96
Remaining number of users is 95
Remaining number of users is 94
Remaining number of users is 93
Remaining number of users is 92
Remaining number of users is 91
Remaining number of users is 90
Remaining number of users is 89
Remaining number of users is 88
Remaining number of users is 87
Remaining number of users is 86
Remaining number of users is 85
Remaining number of users is 84
Remaining number of users is 83
Remaining number of users is 82
Remaining number of users is 81
Remaining number of users is 80
Remaining number of users is 79
Remaining number of users is 78
Remaining number of users is 77
Remaining number of users is 76
Remaining number of users is 75
Remaining number of users is 74
Remaining number of users is 73
Remaining number of users is 72
Remaining number of users is 71
Remaining number of users is 70
Remaining number of users is 69
Remaining number of users is 68
Remaining number of users is 67
Remaining number of users is 66
Remaining number of users is 65
Remaining number of users is 64
Remaining number of users is 63
Remaining number of users is 62
Remaining number of users is 61
Remaining number of users is 60
Remaining number of users is 59
Remaining number of users is 58
Remaining number of users is 57
Remaining number of users is 56
Remaining number of users is 55
Remaining number of users is 54
Remaining number of users is 53
Remaining number of users is 52
Remaining number of users is 51
Remaining number of users is 50
Remaining number of users is 49
Remaining number of users is 48
Remaining number of users is 47
Remaining number of users is 46
Remaining number of users is 45
Remaining number of users is 44
Remaining number of users is 43
Remaining number of users is 42
Remaining number of users is 41
Remaining number of users is 40
Remaining number of users is 39
Remaining number of users is 38
Remaining number of users is 37
Remaining number of users is 36
Remaining number of users is 35
Remaining number of users is 34
Remaining number of users is 33
Remaining number of users is 32
Remaining number of users is 31
Remaining number of users is 30
Remaining number of users is 29
Remaining number of users is 28
Remaining number of users is 27
Remaining number of users is 26
Remaining number of users is 25
Remaining number of users is 24
Remaining number of users is 23
Remaining number of users is 22
Remaining number of users is 21
Remaining number of users is 20
Remaining number of users is 19
Remaining number of users is 18
Remaining number of users is 17
Remaining number of users is 16
Remaining number of users is 15
Remaining number of users is 14
Remaining number of users is 13
Remaining number of users is 12
Remaining number of users is 11
Remaining number of users is 10
Remaining number of users is 9
Remaining number of users is 8
Remaining number of users is 7
Remaining number of users is 6

Remaining number of users is 5
Remaining number of users is 4
Remaining number of users is 3
Remaining number of users is 2
Remaining number of users is 1
Remaining number of users is 0

In [36]:
predictions_collaborative = Ten_Recommendation_Each_User.Product_ids

In [37]:
import math
def indicators_5(rankedList, testList):
    
    Hits_i = 0
    #Len_R = 0
    Len_T = len(testList) # maximum number of unique users
    #MRR_i = 0
    HR_i = 0
    HR_i2 = 0
    NDCG_i = 0    
    count = 0

    for i in range(len(testList)):
        for j in testList[i]:
            count = count + 1 #number of users+product combination
    
    for i in range(len(rankedList)):
        for j in range(len(rankedList[i])):
            for k in range(len(testList[i])):
                if testList[i][k]==rankedList[i][j]:
                    Hits_i+=1
                    HR_i+=1
                    HR_i2+=1
                    #MRR_i+=1/(j+1)   
                    NDCG_i+=1/(math.log2(1+j+1))
                    break
    HR_i/=Len_T #hit rate over total number of unique users
    HR_i2/=count #hit rate over total number of users+product combination
    if Hits_i == 0:
        NDCG_i = 0
    else:
        NDCG_i/=Hits_i #Dividing by Hits_i is a common way to normalize the NDCG score, and it can be useful when we don't know the ideal ranking (i.e., we don't know the IDCG). In this case, we assume that the ideal ranking contains all relevant items in the test set, and we normalize the NDCG score by the number of relevant items in the test set (i.e., Hits_i).
    print(Hits_i)
    print(f'HR_method1={HR_i}')
    print(f'HR_method2={HR_i2}')
    print(f'NDCG={NDCG_i}')

In [38]:
test_list = []
for i in test_set_userids:
    test_list.append(df_test[df_test['User_id'] == i]['Product_id'].tolist())

actual_test = pd.DataFrame(matching_users,columns=['user_id'])
actual_test['bought'] = test_list
actual_test

     user_id           bought
0       8193         [1362.0]
1       2051           [32.0]
2       8196         [1079.0]
3       6154          [233.0]
4       6155           [55.0]
..       ...              ...
502     8172         [1251.0]
503     4081           [73.0]
504     6134          [154.0]
505     8182  [972.0, 1227.0]
506     8186          [177.0]

[507 rows x 2 columns]

In [39]:
indicators_5(predictions_collaborative,test_list)

6
HR_method1=0.011834319526627219
HR_method2=0.010291595197255575
NDCG=0.4083047009638406